name: Deploy to GreenGeeks

on: 
  push: 
    branches: 
      - master

jobs: 
  deploy: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GreenGeeks
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./wp-content/themes/theme
          server-dir: /path/to/your/site/wp-content/themes/theme